apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solia-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: solia.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: solia-api-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: solia-client-service
                port:
                  number: 80
