apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongo-deployment.yaml
  - mongo-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - client-deployment.yaml
  - client-service.yaml
  - mongo-secret.yaml
  - ingress.yaml
