apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: bW9yb3M=        # base64 for 'moros'
  password: c29saWFwYXNz     # base64 for 'soliapass'
  jwt_secret: eW91cl9qd3Rfc2VjcmV0  # base64 for 'your_jwt_secret'
